# Generated by Django 5.1.6 on 2025-02-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WordCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Word Categories",
            },
        ),
        migrations.CreateModel(
            name="WordGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="word_groups", to="portal.wordcategory"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Study_Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("study_activity_id", models.IntegerField()),
                (
                    "Group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_sessions",
                        to="portal.wordgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Study_Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "study_session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="portal.study_sessions",
                    ),
                ),
                (
                    "Group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_activities",
                        to="portal.wordgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Words",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Swahili", models.CharField(max_length=200)),
                ("Pronounciation", models.CharField(max_length=200)),
                ("English", models.CharField(max_length=200)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="words", to="portal.wordcategory"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Words",
            },
        ),
        migrations.AddField(
            model_name="wordgroup",
            name="words",
            field=models.ManyToManyField(related_name="word_groups", to="portal.words"),
        ),
        migrations.CreateModel(
            name="Word_Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct", models.BooleanField()),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "study_session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portal.study_sessions",
                    ),
                ),
                (
                    "word_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.words"
                    ),
                ),
            ],
        ),
    ]
